app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#home:
    # path:           /{_locale}/home
    # defaults:       { _controller: AppBundle:Home:returnNavbar }
    # requirements:   {"_locale": "en|fr"}
