<?php

/* Gozpeak/views/bootstrap-3.3.7-dist/js/npm.js */
class __TwigTemplate_4d2078f2145b6b2180842ae5493d778cf2ba8084bc96d14e4074fb8f208e4db9 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_e3053bc683def7a8be8f9d47e731fea2dd1166eb7b0b3fb48e15eedb6ef95941 = $this->env->getExtension("Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension");
        $__internal_e3053bc683def7a8be8f9d47e731fea2dd1166eb7b0b3fb48e15eedb6ef95941->enter($__internal_e3053bc683def7a8be8f9d47e731fea2dd1166eb7b0b3fb48e15eedb6ef95941_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "Gozpeak/views/bootstrap-3.3.7-dist/js/npm.js"));

        $__internal_37f30926b0ecbe410f0ebdda45fb975e2cb18f7e43e7e194a9bf618d73d19554 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_37f30926b0ecbe410f0ebdda45fb975e2cb18f7e43e7e194a9bf618d73d19554->enter($__internal_37f30926b0ecbe410f0ebdda45fb975e2cb18f7e43e7e194a9bf618d73d19554_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "Gozpeak/views/bootstrap-3.3.7-dist/js/npm.js"));

        // line 1
        echo "// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')";
        
        $__internal_e3053bc683def7a8be8f9d47e731fea2dd1166eb7b0b3fb48e15eedb6ef95941->leave($__internal_e3053bc683def7a8be8f9d47e731fea2dd1166eb7b0b3fb48e15eedb6ef95941_prof);

        
        $__internal_37f30926b0ecbe410f0ebdda45fb975e2cb18f7e43e7e194a9bf618d73d19554->leave($__internal_37f30926b0ecbe410f0ebdda45fb975e2cb18f7e43e7e194a9bf618d73d19554_prof);

    }

    public function getTemplateName()
    {
        return "Gozpeak/views/bootstrap-3.3.7-dist/js/npm.js";
    }

    public function getDebugInfo()
    {
        return array (  25 => 1,);
    }

    /** @deprecated since 1.27 (to be removed in 2.0). Use getSourceContext() instead */
    public function getSource()
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 1.27 and will be removed in 2.0. Use getSourceContext() instead.', E_USER_DEPRECATED);

        return $this->getSourceContext()->getCode();
    }

    public function getSourceContext()
    {
        return new Twig_Source("// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')", "Gozpeak/views/bootstrap-3.3.7-dist/js/npm.js", "/root/Gozpeak/app/Resources/views/Gozpeak/views/bootstrap-3.3.7-dist/js/npm.js");
    }
}
