<?php

/* Gozpeak/views/js/npm.js */
class __TwigTemplate_e86925ac4ffa832b3a90b97beb5f5525d6a1a94d3f42141bfecd43826bc32a57 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_33a36072796c62ca2155fa6ca076b88459540f0004be25fc9dce06d52d5a2147 = $this->env->getExtension("Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension");
        $__internal_33a36072796c62ca2155fa6ca076b88459540f0004be25fc9dce06d52d5a2147->enter($__internal_33a36072796c62ca2155fa6ca076b88459540f0004be25fc9dce06d52d5a2147_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "Gozpeak/views/js/npm.js"));

        $__internal_ccb6342be78dbb33de31f737b885b4da0568a66dd86bf28233f9d9c1152430b6 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_ccb6342be78dbb33de31f737b885b4da0568a66dd86bf28233f9d9c1152430b6->enter($__internal_ccb6342be78dbb33de31f737b885b4da0568a66dd86bf28233f9d9c1152430b6_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "Gozpeak/views/js/npm.js"));

        // line 1
        echo "// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')";
        
        $__internal_33a36072796c62ca2155fa6ca076b88459540f0004be25fc9dce06d52d5a2147->leave($__internal_33a36072796c62ca2155fa6ca076b88459540f0004be25fc9dce06d52d5a2147_prof);

        
        $__internal_ccb6342be78dbb33de31f737b885b4da0568a66dd86bf28233f9d9c1152430b6->leave($__internal_ccb6342be78dbb33de31f737b885b4da0568a66dd86bf28233f9d9c1152430b6_prof);

    }

    public function getTemplateName()
    {
        return "Gozpeak/views/js/npm.js";
    }

    public function getDebugInfo()
    {
        return array (  25 => 1,);
    }

    /** @deprecated since 1.27 (to be removed in 2.0). Use getSourceContext() instead */
    public function getSource()
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 1.27 and will be removed in 2.0. Use getSourceContext() instead.', E_USER_DEPRECATED);

        return $this->getSourceContext()->getCode();
    }

    public function getSourceContext()
    {
        return new Twig_Source("// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')", "Gozpeak/views/js/npm.js", "/root/Gozpeak/app/Resources/views/Gozpeak/views/js/npm.js");
    }
}
